# Sử dụng node_modules truyền thống để đảm bảo Expo/React Native hoạt động
nodeLinker: node-modules

# HDD OPTIMIZATION: Sử dụng Hardlinks để tránh copy file vật lý nhiều lần
nmMode: classic

# HDD OPTIMIZATION: Dùng Global Cache để dùng chung package giữa các project trên máy
enableGlobalCache: true

# Tắt nén để giảm tải cho CPU khi ghi file vào HDD
compressionLevel: 0

# Giới hạn hoisting để tránh làm phình node_modules ở root
nmHoistingLimits: workspaces