export const PROVINCES = [
  { name: "An Giang", id: "an-giang" },
  { name: "Bắc Ninh", id: "bac-ninh" },
  { name: "Cà Mau", id: "ca-mau" },
  { name: "Cần Thơ", id: "can-tho" },
  { name: "Cao Bằng", id: "cao-bang" },
  { name: "Đà Nẵng", id: "da-nang" },
  { name: "Đắk Lắk", id: "dak-lak" },
  { name: "Điện Biên", id: "dien-bien" },
  { name: "Đồng Nai", id: "dong-nai" },
  { name: "Gia Lai", id: "gia-lai" },
  { name: "Hà Nội", id: "ha-noi" },
  { name: "Hà Tĩnh", id: "ha-tinh" },
  { name: "Hải Phòng", id: "hai-phong" },
  { name: "Huế", id: "hue" },
  { name: "Hưng Yên", id: "hung-yen" },
  { name: "Khánh Hòa", id: "khanh-hoa" },
  { name: "Lai Châu", id: "lai-chau" },
  { name: "Lâm Đồng", id: "lam-dong" },
  { name: "Lạng Sơn", id: "lang-son" },
  { name: "Lào Cai", id: "lao-cai" },
  { name: "Nghệ An", id: "nghe-an" },
  { name: "Ninh Bình", id: "ninh-binh" },
  { name: "Phú Thọ", id: "phu-tho" },
  { name: "Quảng Ngãi", id: "quang-ngai" },
  { name: "Quảng Ninh", id: "quang-ninh" },
  { name: "Quảng Trị", id: "quang-tri" },
  { name: "Sơn La", id: "son-la" },
  { name: "Tây Ninh", id: "tay-ninh" },
  { name: "Thái Nguyên", id: "thai-nguyen" },
  { name: "Thanh Hóa", id: "thanh-hoa" },
  { name: "TP. Hồ Chí Minh", id: "tp-ho-chi-minh" },
  { name: "Tuyên Quang", id: "tuyen-quang" },
  { name: "Vĩnh Long", id: "vinh-long" },
] as const;

export type ProvinceId = typeof PROVINCES[number]["id"];
