export enum ENUM_ACTIVITY_TYPE {
  SYSTEM = 'SYSTEM',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_RESET_PASSWORD = 'USER_RESET_PASSWORD',
  USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
  USER_UPDATE_ROLE = 'USER_UPDATE_ROLE',
  USER_UPDATE_STATUS = 'USER_UPDATE_STATUS',
  USER_UPDATE_MOBILE = 'USER_UPDATE_MOBILE',
  USER_RESTORE = 'USER_RESTORE',
  USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE',
  USER_UPDATE_PREFERENCES = 'USER_UPDATE_PREFERENCES',
  USER_UPDATE_LOCATION = 'USER_UPDATE_LOCATION',
  USER_UPDATE_VOLUNTEER = 'USER_UPDATE_VOLUNTEER',

  // Reset Password
  USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST',
  USER_RESET_PASSWORD_VERIFY = 'USER_RESET_PASSWORD_VERIFY',
  // USER_RESET_PASSWORD already exists, likely for the final step

  // Report
  REPORT_CREATE = 'REPORT_CREATE',
  REPORT_UPDATE = 'REPORT_UPDATE',
  REPORT_DELETE = 'REPORT_DELETE',
  REPORT_ACCEPT = 'REPORT_ACCEPT',
  REPORT_REJECT = 'REPORT_REJECT',
  REPORT_COMPLETE = 'REPORT_COMPLETE',
  REPORT_CANCEL = 'REPORT_CANCEL',
}
