export enum ENUM_SHELTER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  FULL = 'FULL',
  CLOSED = 'CLOSED'
}

export enum ENUM_SHELTER_TYPE {
  SCHOOL = 'SCHOOL',
  COMMUNITY_CENTER = 'COMMUNITY_CENTER',
  GYM = 'GYM',
  PAGODA = 'PAGODA',
  CHURCH = 'CHURCH',
  OTHER = 'OTHER',
  EVACUATION = 'EVACUATION',
  WAREHOUSE = 'WAREHOUSE',
  MEDICAL = 'MEDICAL',
  TEMPORARY = 'TEMPORARY',
  OFFICIAL = 'OFFICIAL'
}
