export enum ENUM_SHELTER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  FULL = 'FULL',
  CLOSED = 'CLOSED'
}

export enum ENUM_SHELTER_TYPE {
  EVACUATION = 'EVACUATION',
  WAREHOUSE = 'WAREHOUSE',
  MEDICAL = 'MEDICAL',
  TEMPORARY = 'TEMPORARY'
}
